### ISSUE TITLE
border and text color

### ISSUE THREAD

**Issue by ogansser** [J-Siu/hugo-theme-sk3#27] opened 2021-04-07 17:16 UTC
Hi, thank you for the nice theme. 

I want to change the color in the theme. bg and link is able to change. border and text is always white no matter which color I use. 

Thanx

**Comment by J-Siu** [comment] 2021-04-08 02:51
Thank you for reporting.

Border color was caused by missing css attributes in the box element.
Text color was caused by wrong variable name in template header file.

They are both fixed now. Please pull the master again and give it a try.

**Comment by ogansser** [comment] 2021-04-08 07:13
Hi, thanks, how can pull the master did not clone the repository? I made a local project with blogdown::new_site(). Otherwise make new_site and copy my posts and my config.yaml?

**Comment by ogansser** [comment] 2021-04-08 07:22
Second way work, bg color and text corol work. Thank you!

**Comment by J-Siu** [comment] 2021-04-08 10:02
Thank you for update!

May I close the issue?

**Comment by ogansser** [comment] 2021-04-08 11:25
Yes, thanks. Shortcode for youtube Video also does not work.

In config.yaml I wrote:
enableInlineShortcodes: true

In Rmd:
{{< youtube buiLez6AMU8 >}}

Watch the final site: http://gansser.de/post/choughs-verhaltenstypisierung/

**Comment by J-Siu** [comment] 2021-04-08 11:43
I checked your page, it maybe caused by missing space before the closing delimiter.

Current:
```
{{< youtube id=“buiLez6AMU8”>}}
```
Try adding a space before `>}}`, like following:
```
{{< youtube id=“buiLez6AMU8” >}}
```

**Comment by ogansser** [comment] 2021-04-08 13:03
{{< youtube buiLez6AMU8 >}}

still does not work. Must be something different. I mad another site with another theme for my sister, there it works:

https://isigansser.netlify.app/post/ms/

**Comment by ogansser** [comment] 2021-04-08 13:13
HTML Site shows without space. In my Rmd there is a space. Strange.

**Comment by J-Siu** [comment] 2021-04-08 13:23
Can you test your sister site with my theme?
Because the short code is working in my example site https://sk3.jsiu.dev/post/rich-content/ , and the md for that page is https://github.com/gohugoio/hugoBasicExample/blob/master/content/post/rich-content.md

**Comment by ogansser** [comment] 2021-04-08 13:30
how can I change the theme of a site?

**Comment by J-Siu** [comment] 2021-04-08 13:34
If you use git, go to root of your hugo site:

```
git clone https://github.com/J-Siu/hugo-theme-sk3 themes/sk3
```
Then in the config.toml file, look for the line `theme = ....` and change it to
```
theme=sk3
```

**Comment by J-Siu** [comment] 2021-04-09 01:42
I created a RStudio testing project https://github.com/J-Siu/blogdown-sk3-test
I am able to see the embedded youtube video inside the viewer. So I am closing this for now.

**Closed by J-Siu** 2021-04-09 01:42 UTC
Labels: bug
